### ISSUE TITLE
Seeing failed negotiations?

### ISSUE THREAD

**Issue by jacksondc** [yasserfarouk/scml-vis#5]
If I select a contract, I can see the history of offers in the negotiation that led to the contract. Is there a way to see the histories of failed negotiations as well?

**Comment by yasserfarouk** [comment]
Hi Jackson

Yes you can. Just check the negotiations list. You need to enable it on the left bar first. 

Note that for this list to exist, the simulation must be run from the start with `save_negotiations=True`.

You can check whether that is the case by looking for a `negotiations.csv` file in the logs.

**Comment by jacksondc** [comment]
I see now, thank you!
