### ISSUE TITLE
ImportError: cannot import name 'cli' from 'streamlit' 

### ISSUE THREAD

**Issue by a4rcvv** [yasserfarouk/scml-vis#9]
**Describe the bug**

`ImportError` is raised when I run `scmlv` command.

```
Traceback (most recent call last):
  File "/Users/a4rcvv/Documents/projects/scml-vis/venv/bin/scmlv", line 5, in <module>
    from scml_vis.cli import main
  File "/Users/a4rcvv/Documents/projects/scml-vis/src/scml_vis/cli.py", line 21, in <module>
    import scml_vis.presenter as presenter
  File "/Users/a4rcvv/Documents/projects/scml-vis/src/scml_vis/presenter.py", line 17, in <module>
    from streamlit import cli as stcli
ImportError: cannot import name 'cli' from 'streamlit' (/Users/a4rcvv/Documents/projects/scml-vis/venv/lib/python3.8/site-packages/streamlit/__init__.py)
``` 

**To Reproduce**
1. Run command `scmlv`.

**Expected behavior**
Nothing error happens.

**System (please complete the following information):**
- `scml-vis` version: 0.2.11
- Python version: 3.8.13
- OS: macOS 12.4

**Additional context**

From version 1.12.0 of streamlit, it seems that `streamlit.cli` has been moved to `streamlit.web.cli`.

**Comment by a4rcvv** [comment]
I made the pull request (#10) but I don't know the details of this library, so please use it for your reference.

**Comment by yasserfarouk** [comment]
Thank you. We will check it as soon as possible.

**Comment by yasserfarouk** [comment]
Merged. Thanks
